# Generated by Django 4.0.4 on 2022-05-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я категорії")),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категорії',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name="Ім'я продукта")),
                ('slug', models.SlugField(unique=True)),
                ('product_code', models.IntegerField(blank=True, default='0003001', verbose_name='Код продукту')),
                ('img', models.ImageField(upload_to='', verbose_name='Фотокартка')),
                ('qty_product', models.IntegerField(default=1, verbose_name='Кількість товару')),
                ('price', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Ціна')),
                ('description', models.TextField(verbose_name='Опис')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Продукція',
                'verbose_name_plural': 'Продукція',
            },
        ),
    ]
