# Generated by Django 4.0.4 on 2022-06-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_product_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Нова ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
    ]
