# Generated by Django 4.0.4 on 2022-06-02 21:10

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_product_title_alter_productimage_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ordered',
            field=models.IntegerField(default=0, verbose_name='Замовлено разів'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to=mainapp.models.user_directory_path, verbose_name='Фотокартка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.IntegerField(blank=True, default=613587, verbose_name='Код продукту'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=models.ImageField(upload_to=mainapp.models.user_directory_path),
        ),
    ]
