# Generated by Django 4.0.4 on 2022-06-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_product_ordered_alter_product_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.IntegerField(blank=True, default=804941, verbose_name='Код продукту'),
        ),
    ]
