# Generated by Django 4.0.4 on 2022-05-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='superuser',
            field=models.BooleanField(default=False, verbose_name='Is Super User'),
        ),
    ]
