# Generated by Django 4.0.4 on 2022-06-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('image', models.ImageField(upload_to='main_slider/', verbose_name='Фотокартка')),
                ('slug', models.SlugField(unique=True)),
                ('post', models.BooleanField(default=False, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Слайдер на головній сторінці',
                'verbose_name_plural': 'Слайдер на головній сторінці',
            },
        ),
    ]
