# Generated by Django 4.0.4 on 2022-05-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_customer_alter_order_buying_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer'),
        ),
    ]
